[2025-01-22T13:17:59.360+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T13:17:59.373+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-run manual__2025-01-22T13:02:36.854235+00:00 [queued]>
[2025-01-22T13:17:59.380+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-run manual__2025-01-22T13:02:36.854235+00:00 [queued]>
[2025-01-22T13:17:59.382+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-01-22T13:17:59.404+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-run> on 2025-01-22 13:02:36.854235+00:00
[2025-01-22T13:17:59.408+0000] {standard_task_runner.py:72} INFO - Started process 105129 to run task
[2025-01-22T13:17:59.411+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake1', 'dbt_tasks.dbt-run', 'manual__2025-01-22T13:02:36.854235+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmponl7ambw']
[2025-01-22T13:17:59.413+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask dbt_tasks.dbt-run
[2025-01-22T13:17:59.470+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-run manual__2025-01-22T13:02:36.854235+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T13:17:59.553+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T13:02:36.854235+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T13:02:36.854235+00:00'
[2025-01-22T13:17:59.555+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T13:17:59.556+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T13:17:59.557+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-run state:running start_date:2025-01-22 13:17:59.374757+00:00
[2025-01-22T13:17:59.558+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake1 and current dag run status:running
[2025-01-22T13:17:59.559+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T13:17:59.561+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T13:17:59.563+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T13:17:59.570+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T13:18:04.581+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-22T13:18:04.585+0000] {process_utils.py:132} INFO - Sending 15 to group 105129. PIDs of all processes in the group: [105131, 105129]
[2025-01-22T13:18:04.586+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 105129
[2025-01-22T13:18:04.587+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-22T13:18:04.588+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-01-22T13:18:04.595+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-01-22T13:18:04.675+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T13:18:04.677+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 13:17:59.374757+00:00 end:2025-01-22 13:18:04.674920+00:00 duration:5.300163
[2025-01-22T13:18:04.678+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-run> dag:<DAG: airflow_dbt_snowflake1> dagrun:<DagRun airflow_dbt_snowflake1 @ 2025-01-22 13:02:36.854235+00:00: manual__2025-01-22T13:02:36.854235+00:00, state:running, queued_at: 2025-01-22 13:02:36.931610+00:00. externally triggered: True>
[2025-01-22T13:18:04.680+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-01-22T13:18:04.681+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_dbt_snowflake1, task_id=dbt_tasks.dbt-run, run_id=manual__2025-01-22T13:02:36.854235+00:00, execution_date=20250122T130236, start_date=20250122T131759, end_date=20250122T131804
[2025-01-22T13:18:04.725+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T13:18:04.766+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=105131, status='terminated', started='13:17:59') (105131) terminated with exit code None
[2025-01-22T13:18:04.768+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=105129, status='terminated', exitcode=2, started='13:17:59') (105129) terminated with exit code 2
